#!/bin/bash
#Menu
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"

CPU=`egrep 'GHz' /proc/cpuinfo` 
IP=`dig +short myip.opendns.com @resolver1.opendns.com` 
UP=`uptime`
HT=`hostname`

echo -e ""
echo -e "\e[35;1m IP        : \e[32;1m $IP"
echo -e "\e[35;1m Server    : \e[32;1m $HT"
echo -e "\e[35;1m Akun aktif: \e[32;1m $JUMLAH"
echo -e ""
echo -e "\e[40;38;5;21m=========================\e[30;48;5;9m✩✩✩ M E N U ✩✩✩\e[40;38;5;21m=========================\e[0m"
echo -e "\e[36;1m SSH/VPN :" 
echo -e "\e[38;5;226m[1]menu             |: \e[38;5;130m[Menampilkan Daftar Perintah]"
echo -e "\e[38;5;226m[2]user-new         |: \e[38;5;130m[Buat Akun SSH / OpenVPN]"
echo -e "\e[38;5;226m[3]create-trial     |: \e[38;5;130m[Buat Akun Trial]"
echo -e "\e[38;5;226m[4]delete-user      |: \e[38;5;130m[Hapus Akun SSH / OpenVPN]"
echo -e "\e[38;5;226m[5]user-list        |: \e[38;5;130m[Cek Daftar Akun Aktif & Masa Expired]"
echo -e "\e[38;5;226m[6]user-login       |: \e[38;5;130m[Monitoring Dropbear,OpenSSH,OpenVPN]"
echo -e "\e[38;5;226m[7]dropmon          |: \e[38;5;130m[Monitoring Dropbear]"
echo -e "\e[38;5;226m[8]limit-login      |: \e[38;5;130m[Kill Multi Login]"
echo -e "\e[38;5;226m[9]anner-edit       |: \e[38;5;130m[Edit Banner SSH Login]"
echo -e ""
echo -e "\e[40;38;5;124m  SERVER SETTING\e[0m"
echo -e "\e[38;5;226m[10]Speedtest        |: \e[38;5;130m[Cek Kecepatan VPS]"
echo -e "\e[38;5;226m[11]Info             |: \e[38;5;130m[Menampilkan Informasi Sistem]"
echo -e "\e[38;5;226m[12]Mem-info         |: \e[38;5;130m[Info Script Auto Install]"rt semua service]"
echo -e "\e[38;5;226m[13]Resvis           |: \e[38;5;130m[restart semua service]"
echo -e "\e[38;5;226m[14]Restart-webmin   |: \e[38;5;130m[Restart Webmin] Service"
echo -e "\e[38;5;226m[15]Restart-ssh      |: \e[38;5;130m[Restart ssh service]"
echo -e "\e[38;5;226m[16]Restart-dropbear |: \e[38;5;130m[Restart dropbear service]"
echo -e "\e[38;5;226m[17]Restart-squid    |: \e[38;5;130m[Restart squid service]"
echo -e "\e[38;5;226m[18]Restart-openvpn  |: \e[38;5;130m[Restart openvpn service]"
echo -e "\e[38;5;226m[19]Change-hostname  |: \e[38;5;130m[Merubah hostname server]"
echo -e "\e[38;5;226m[20]Change-password  |: \e[38;5;130m[Merubah password server]"
echo -e "\e[38;5;226m[21]Change-dropbear  |: \e[38;5;130m[Merubah dropbear port]"
echo -e "\e[38;5;226m[22]Change-squid3    |: \e[38;5;130m[Merubah squid3 port]"
echo -e "\e[38;5;226m[23]Create-ocs       |: \e[38;5;130m[Aktifkan OCS panel]"
echo -e "\e[38;5;226m[24]Change-sslwebmin |: \e[38;5;130m[Error ssl di webmin ganti ssl=1 ke ssl=0]"
echo -e "\e[38;5;226m[25]About-team       |: \e[38;5;130m[Info Script Auto Install]"
echo -e "\e[38;5;226m[26]Reboot           |: \e[38;5;130m[Reboot VPS]"
echo -e "\e[31;1m [27]Update              |: \e[38;5;130m[Update Script]"
echo -e ""
echo -e "\e[38;5;226m [0]exit             |: \e[32;1m[Keluar Dari Menu]"
echo -e "\e[40;38;5;21m==================\e[30;48;5;9m✩✩✩CopyLeft@OrangKUatSabahanTerkini✩✩✩\e[40;38;5;21m===================\e[0m"
echo -e "\e[37;1m"

read -p "Masukkan pilihan anda, lalu tekan ENTER:" nomer

if [ "$nomer" = "1" ]
then
    menu
elif [ "$nomer" = "2" ]
then
    user-new
elif [ "$nomer" = "3" ]
then
    create-trial
elif [ "$nomer" = "4" ]
then
    delete-user
elif [ "$nomer" = "5" ]
then
    user-list
elif [ "$nomer" = "6" ]
then
    user-login
elif [ "$nomer" = "7" ]
then
   ./dropmon.sh    
elif [ "$nomer" = "8" ]
then
    limit-login
elif [ "$nomer" = "9" ]
then
    banner-edit
elif [ "$nomer" = "10" ]
then
    speedtest
elif [ "$nomer" = "11" ]
then
    info
elif [ "$nomer" = "12" ]
then
    mem-info
elif [ "$nomer" = "13" ]
then
    resvis
elif [ "$nomer" = "14" ]
then
    /etc/init.d/webmin restart
elif [ "$nomer" = "15" ]
then
    service ssh restart
elif [ "$nomer" = "16" ]
then
    service dropbear restart

elif [ "$nomer" = "17" ]
then
    service squid3 restart
elif [ "$nomer" = "18" ]
then
    service openvpn restart

elif [ "$nomer" = "19" ]
then
    nano /etc/hostname
	hostname
elif [ "$nomer" = "20" ]
then
    passwd
elif [ "$nomer" = "21" ]
then
    nano /etc/default/dropbear
elif [ "$nomer" = "22" ]
then
    nano /etc/squid3/squid.conf
	service squid3 restart
elif [ "$nomer" = "23" ]
then
    create-ocs
elif [ "$nomer" = "24" ]
then
    nano /etc/webmin/miniserv.conf
elif [ "$nomer" = "25" ]
then
    about-team
elif [ "$nomer" = "26" ]
then
    reboot
elif [ "$nomer" = "27" ]
then
    update
elif [ "$nomer" = "0" ]
then
    exit
cd /bin
wget https://raw.githubusercontent.com/KeningauVPS/menu2/master/update
chmod +x update
else 
    menu
fi

echo -e "\e[32;1m"	
